version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: travel_parser
      POSTGRES_PASSWORD: dev_password_123
      POSTGRES_DB: travel_parser_dev
    ports:
      - "5433:5432"  # Using 5433 to avoid conflicts with any existing PostgreSQL
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U travel_parser -d travel_parser_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:
