openapi: 3.1.0
info:
  title: Travel Email Parser API
  version: 1.0.0
  description: AI-powered travel email parsing API

servers:
  - url: http://localhost:3000/api/v1
    description: Development server

paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: API is healthy
